#!/usr/bin/python
# -*- coding: iso-8859-1 -*-
#librairies nécessaire au script
import os, sys
import argparse

def get_parser():


    parser = argparse.ArgumentParser(description='MetARTwork for slurm')

    parser.add_argument('-i', action="store", dest='TSV', 
                     type=str, required=True, help="ARTwork TSV file (REQUIRED)")
    
    parser.add_argument('-n', action="store", dest='NASBIO1_PATH', 
                        type=str, default='mnt/NAS/NASBIO1/', help='NASBIO1 path (default:mnt/NAS/NASBIO1/)')

    parser.add_argument('-T', action="store", dest='nbThreads', 
                        type=str, default='40', help='Number of threads to use (default:40)')
    
    parser.add_argument('--alerte', dest='alerte', action='store_true', 
                        help='Use Alerte_rouge partition', default=False)

    return parser


#main function	
def main():
    
    parser=get_parser()

    #print parser.help if no arguments
    if len(sys.argv)==1:
        parser.print_help()
        sys.exit(1)

    Arguments=parser.parse_args()
    
    if Arguments.alerte:
        script = " /global/conda/bin/ARtWORK_slurm_alerte "
    else:
        script = " /global/conda/bin/ARtWORK_slurm "

    tab_file = Arguments.TSV
    tab=open(tab_file, 'r')
    lines=tab.readlines()
    header=True
    for line in lines :
        if header:
            header=False
            continue
        else :
            line = line.rstrip()
            line = line.split('\t')
            id = line[2]
            cmd = "sbatch  --cpus-per-task=" + Arguments.nbThreads + " -J \"ARtWORK_" + id + "\"" + script + \
            Arguments.NASBIO1_PATH + " " + Arguments.nbThreads + " " + line[0] + " " + line[1] + " \"" + line[2] + "\" " + line[3] + " " + \
            line[4] + " " + line[5] + " " + line[6]
            print(cmd)
            os.system(cmd)
                
if __name__ == "__main__":
	main()					
                
